stages:
  - install_deps
  - build
  - deploy

Install Dependencies:
  stage: install_deps
  tags:
    - frontend
  image: node:latest
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
  script:
    - npm install --progress=false
  only:
    - develop
    - master
    - main
    - /^release\/[0-9]+(?:.[0-9]+)+$/ # regular expression

Build_Dev:
  stage: build
  tags:
    - frontend
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
    policy: pull
  before_script:
    - export NODE_OPTIONS="--max-old-space-size=4096"
  script:
    - CI=false npm run build:dev
    - pipeline_id=`echo "$CI_PIPELINE_ID"`
    - main_version=`cat build/version`
    - date_format=`echo $(date '+%Y%m%d')`
    - 'version="${main_version}.${pipeline_id}.${date_format}"'
    - echo $version > build/version
    - mv build build_dev
  artifacts:
    name: build_dev
    paths:
      - build_dev
  only:
    - develop

Build_Prod:
  stage: build
  tags:
    - frontend
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
    policy: pull
  before_script:
    - export NODE_OPTIONS="--max-old-space-size=4096"
  script:
    - CI=false npm run build:prod
    - pipeline_id=`echo "$CI_PIPELINE_ID"`
    - main_version=`cat build/version`
    - date_format=`echo $(date '+%Y%m%d')`
    - 'version="${main_version}.${pipeline_id}.${date_format}"'
    - echo $version > build/version
    - mv build build_prod
  artifacts:
    name: build_prod
    paths:
      - build_prod
  only:
    - master
    - main

Deploy Test:
  stage: deploy
  tags:
    - frontend
  image: ubuntu
  script:
    - echo "Deploying to server"
    - rsync -avz --delete build_dev/ /var/www/html/build_dev
    - rm -rf build_dev
    - echo "Deployed"
  only:
    - develop

Deploy Prod:
  stage: deploy
  tags:
    - frontend
  image: ubuntu
  script:
    - echo "Deploying to server"
    - rsync -avz --delete build_prod/ /var/www/html/build_prod
    - rm -rf build_prod
    - echo "Deployed"
  only:
    - master
    - main