export const commonTypes = {

    RELOAD_REQUEST: "RELOAD_REQUEST",
    CLOSE_REQUEST: "CLOSE_REQUEST",
    LOADING_START: "LOADING_START",
    LOADING_FINISH: "LOADING_FINISH",
    SET_HEADER: "SET_HEADER",
    CHANGE_AVATAR: "CHANGE_AVATAR"
};
