export const URIS = {
    DASHBOARD: "/dashboard",
    LOGIN: "/login",
    SIGN_UP: "/sign-up",
    RESET_PASSWORD: "/reset-password",
    CHANGE_PASSWORD: "/change-password",
    BUSINESS: "/business",
    DEPARTMENT: "/department",
    ACCOUNT: "/account",
    ACCOUNT_INFO: "/account/info",
    ACCOUNT_SECURITY: "/account/security",
    LANDING_PAGE: "/landing-page",
    PROJECT: "/project/*",
    VIEW_PROJECT: "/project/view",
    PHASE: "/phase/*",
    WORK: "/work/*",
    RESOURCE_TYPE: "/resource-type/*",
    VIEW_PHASE: "/phase/view",
};
